name: Suggestion
description: "Feature that you'd like to see added or changed. Note that newer features will likely only happen in the current/newer version of Minecraft."
title: "[Suggestion]: "
labels: [ "enhancement" ]
body:
  -   type: textarea
      attributes:
        label: Describe the Suggestion
        description: What should be added or changed?
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Screenshots and Videos
        description: If applicable, add screenshots or videos to help explain your suggestion.
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Additional Context
        description: Add any extra context about the suggestion here.
      validations:
        required: false